### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError

### ISSUE THREAD

**Issue by aledv** [artyshko/smd#14]
Since today I have this issue when I use the application:    

> youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug ....

**Comment by artyshko** [comment]
You have to [update](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) **youtube-dl**.
`sudo -H pip3 install --upgrade youtube-dl`

**Comment by aledv** [comment]
yep, after update it working fine!

thanks
