### ISSUE TITLE
Connect smd to Telegram

### ISSUE THREAD

**Issue by alircxa** [artyshko/smd#20]
Hey guys,
Do you have any idea to how can we connect SMD to our telegram bot?
I'll really appreciate if you can help me.
Thanks.

**Comment by artyshko** [comment]
**https://t.me/SpotifyMusicDownloaderBot** - you can use this one.

**Comment by alircxa** [comment]
Yes, I have it, but I want to use my own server when you are down. :(

**Comment by artyshko** [comment]
You can just use the desktop version in this case.
