### ISSUE TITLE
woowwwww!!!

### ISSUE THREAD

**Issue by Grecia1982** [artyshko/smd#32]
greatttttttttttttttttttt man....but the linkkkkkkkkkkkkkk???

**Comment by artyshko** [comment]
### **You have to use git clone for downloading.**
**[Installation.](https://github.com/artyshko/smd#installation)**

**Comment by Grecia1982** [comment]
hello dudeeeeee!!!what you mean my friend?I am not programmer
unfortunately...could you help me pleaseeeeeeeeee???

Στις Σάβ, 7 Δεκ 2019 στις 9:41 π.μ., ο/η Artyshko Mykola <
notifications@github.com> έγραψε:

**Comment by Grecia1982** [comment]
hello dudeeeeee!!!what you mean my friend?I am not programmer unfortunately...could you help me pleaseeeeeeeeee???

**Comment by artyshko** [comment]
### **How to run it on Linux.**
**1. From your shell, install Git using apt-get:**

```
sudo apt-get update
sudo apt-get install git
```
**2. Clone the project to your desktop**

`git clone https://github.com/artyshko/smd.git`

**3. Install all dependencies**

```
pip3 install -r requirements.txt
pip3 install PyQtWebEngine
sudo apt-get install python3-pyqt5.qtwebengine

```
**4. Make files executable**

```
chmod +x main.py
chmod +x run.sh
```
**5. Run it**

- For the CLI version, use:
`./main.py`

- For the GUI version, use:
`./run.sh`
