### ISSUE TITLE
Python dependencys not found on requierements.txt

### ISSUE THREAD

**Issue by hirigataka** [artyshko/smd#38]
when i'm install py dependencys on requirements.txt. I found some problem, here my log

> >     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6dkwhpi0/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6dkwhpi0/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-6dkwhpi0/pygame/pip-egg-info
>          cwd: /tmp/pip-install-6dkwhpi0/pygame/
>     Complete output (18 lines):
>     
>     
>     WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
>     Using UNIX configuration...
>     
>     
>     Hunting dependencies...
>     SDL     : found 1.2.15
>     FONT    : not found
>     IMAGE   : not found
>     MIXER   : not found
>     PNG     : found
>     JPEG    : found
>     SCRAP   : found
>     PORTMIDI: not found
>     PORTTIME: not found
>     FREETYPE: found 23.1.17
>     Missing dependencies
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

thanks for helping and sorry for my bad eng
Edit: I use arch linux

**Comment by DroidZed** [comment]
> when i'm install py dependencys on requirements.txt. I found some problem, here my log
> 
> > > ```
> > > ERROR: Command errored out with exit status 1:
> > > ```
> > 
> > 
> > ```
> >  command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6dkwhpi0/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6dkwhpi0/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-6dkwhpi0/pygame/pip-egg-info
> >      cwd: /tmp/pip-install-6dkwhpi0/pygame/
> > Complete output (18 lines):
> > 
> > 
> > WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
> > Using UNIX configuration...
> > 
> > 
> > Hunting dependencies...
> > SDL     : found 1.2.15
> > FONT    : not found
> > IMAGE   : not found
> > MIXER   : not found
> > PNG     : found
> > JPEG    : found
> > SCRAP   : found
> > PORTMIDI: not found
> > PORTTIME: not found
> > FREETYPE: found 23.1.17
> > Missing dependencies
> > ----------------------------------------
> > ```
> > 
> > 
> > ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
> thanks for helping and sorry for my bad eng
> Edit: I use arch linux

I'm having the same issue here but with ubuntu 18.04

**Comment by TheOldGoldenFish** [comment]
This fixed my issue with pygame:

> `sudo apt-get install python3-pygame`

**Comment by hirigataka** [comment]
fixed 
thanks to @TheOldGoldenFish for helping
