### ISSUE TITLE
"Downloader" in header1.png is misspelled

### ISSUE THREAD

**Issue by kittenparry** [artyshko/smd#4]
In the second preview image called `header1.png` in [README.md](https://github.com/artyshko/smd/blob/master/README.md), word `Downloader` is misspelled as `Downoader`. [Direct image link](https://raw.githubusercontent.com/artyshko/smd/telegram/Data/header1.png).

I suppose the image should be redone in whatever software it originally was done in and re-uploaded.

**Comment by artyshko** [comment]
### **Thanks a lot**
