### ISSUE TITLE
Error starting the app up.

### ISSUE THREAD

**Issue by windowzytch** [artyshko/smd#69]
I don't know what happens but I couldn't get it to work. I'm sure everything required is installed and I followed the instructions step by step.
/ Ubuntu 20.04 Focal Fossa here.

```
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from youtube import Youtube
  File "/home/owz/smd/youtube.py", line 5, in <module>
    from pytube import YouTube
  File "/home/owz/.local/lib/python3.8/site-packages/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "/home/owz/.local/lib/python3.8/site-packages/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "/home/owz/.local/lib/python3.8/site-packages/pytube/extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (/home/owz/.local/lib/python3.8/site-packages/pytube/compat.py)
```

**Comment by computerdude100** [comment]
+1 on this. Followed step by step (although I wish the instructions were more detailed), and I achieve the above result on Ubuntu 20.04 and Python 3.8. Any help would be much appreciated.

**Comment by windowzytch** [comment]
> +1 on this. Followed step by step (although I wish the instructions were more detailed), and I achieve the above result on Ubuntu 20.04 and Python 3.8. Any help would be much appreciated.

I guess it's because of old Python version used. I'll also try different methods to see if I can achieve usage of it. Anyway, thanks for confirming. :)

**Comment by thecloakmaster** [comment]
Try changing the pytube version

**Comment by windowzytch** [comment]
> Try changing the pytube version

Can you tell us how? Because the version it grabs is latest one, which causes the problem.

**Comment by thecloakmaster** [comment]
> > Try changing the pytube version
> 
> Can you tell us how? Because the version it grabs is latest one, which causes the problem.
You can use this code `pip3 install pytube==your pytube version`
Change the pytube version to the one you want. For example,
`pip3 install pytube==9.0`

**Comment by computerdude100** [comment]
> > > Try changing the pytube version
> > 
> > 
> > Can you tell us how? Because the version it grabs is latest one, which causes the problem.
> 
> You can use this code `pip3 install pytube==your pytube version`
> Change the pytube version to the one you want. For example,
> `pip3 install pytube==9.0`

Installing 9.0 fixed _this_ particular issue... brought many more to light but it seems to be the solution for this issue.

**Comment by windowzytch** [comment]
Got it. Thanks for lighting me up, everyone. Now closing the issue as it's resolved now.
