### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by revers3stark26** [artyshko/smd#75]
i have no idea how this works >thanks for making this 
i just wanted to install >  error while installing 😅

revers3stark26@revers3stark26-zscasel:~/smd$ pip3 install -r requirements.txt
Collecting notify2==0.3.1
  Using cached notify2-0.3.1-py2.py3-none-any.whl (8.0 kB)
Collecting spotipy==2.4.4
  Using cached spotipy-2.4.4.tar.gz (15 kB)
Collecting lyricsgenius==1.4.0
  Using cached lyricsgenius-1.4.0-py3-none-any.whl (13 kB)
Collecting lxml==4.3.3
  Using cached lxml-4.3.3.tar.gz (4.4 MB)
Collecting mutagen==1.41.0
  Using cached mutagen-1.41.0.tar.gz (918 kB)
Collecting requests==2.21.0
  Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
Collecting moviepy==0.2.3.5
  Using cached moviepy-0.2.3.5.tar.gz (372 kB)
Collecting imageio==2.3.0
  Using cached imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
Collecting humanize==0.5.1
  Using cached humanize-0.5.1.tar.gz (14 kB)
Collecting pygame==1.9.6
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qmivj_vj/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qmivj_vj/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qmivj_vj/pygame/pip-egg-info            
         cwd: /tmp/pip-install-qmivj_vj/pygame/                                        
    Complete output (20 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: pkg-config: not found
    /bin/sh: 1: pkg-config: not found
    /bin/sh: 1: pkg-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "pkg-config freetype2" failed!
    WARNING: "freetype-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by thecloakmaster** [comment]
This is a problem with the new Python 3.8. I solved this by deleting the pygame version 1.9.6 in the requirements file and typing 2.0.0dev6 in the requirements.txt file. This version works properly with the new Python version. You can also just remove it from the txt file and install it separately by using this command:
`pip3 install pygame==2.0.0dev6`
Hope this will help you.

**Comment by revers3stark26** [comment]
thangs it worked

**Comment by 2ale2** [comment]
Sorry I tried to do this too but, after downlaoding the specivied pygame version specified, is shown this error:

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alant.LAPTOP-8L623GR6\\AppData\\Local\\Temp\\pip-install-_8uvit4w\\pygame_4841866df73f4a97b16a4a5f619c5cf8\\setup.py'"'"'; __file__='"'"'C:\\Users\\alant.LAPTOP-8L623GR6\\AppData\\Local\\Temp\\pip-install-_8uvit4w\\pygame_4841866df73f4a97b16a4a5f619c5cf8\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-pip-egg-info-ik1ulzhf'
         cwd: C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\
    Complete output (42 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\setup.py", line 258, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\buildconfig\config.py", line 208, in main
        deps = CFG.main(**kwds)
      File "C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\buildconfig\config_win.py", line 559, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\buildconfig\download_win_prebuilt.py", line 269, in ask
        update(x86=x86, x64=x64, sdl2=sdl2)
      File "C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\buildconfig\download_win_prebuilt.py", line 252, in update
        download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
      File "C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\buildconfig\download_win_prebuilt.py", line 101, in download_prebuilts
        download_sha1_unzip(url, checksum, temp_dir, 1)
      File "C:\Users\alant.LAPTOP-8L623GR6\AppData\Local\Temp\pip-install-_8uvit4w\pygame_4841866df73f4a97b16a4a5f619c5cf8\buildconfig\download_win_prebuilt.py", line 37, in download_sha1_unzip
        raise ValueError(
    ValueError: url:https://bitbucket.org/llindstrom/pygame/downloads/prebuilt-x64-pygame-1.9.2-20150922.zip should have checksum:3a5af3427b3aa13a0aaf5c4cb08daaed341613ed: Has:edb5e7881027e10d32f6bc504b361d75473bc537:
    Making dir :prebuilt_downloads:
    Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip 0bbac0106358dc99b8ba2401ae6a1c10d3927ca9
    Unzipping :prebuilt_downloads\SDL2-devel-2.0.10-VC.zip:
    Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
    Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
    Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-VC.zip c64d90c1f7d1bb3f3dcfcc255074611f017cdcc4
    Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.14-VC.zip:
    Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
    Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
    Downloading... https://www.ijg.org/files/jpegsr9c.zip 9ca086c960ffc4bff821ba194c8d0a15f69eae09
    Unzipping :prebuilt_downloads\jpegsr9c.zip:
    Downloading... https://bitbucket.org/llindstrom/pygame/downloads/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed

    ---
    For help with compilation see:
        https://www.pygame.org/wiki/CompileWindows
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
